---
version: 2
updates:
  - package-ecosystem: "gomod"
    open-pull-requests-limit: 100
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 100
    directory: "/"
    schedule:
      interval: "daily"
