#!/usr/bin/env ruby

require 'webrick'

raise unless File.readlines('/etc/os-release').grep(/Bionic/).any?

server = WEBrick::HTTPServer.new :Port => ENV['PORT']

server.mount_proc '/' do |request, response|
  response.body = 'Hello World!'
end

trap 'INT' do server.shutdown end

server.start
